export const users = [
  {
    name: 'Store Admin',
    email: 'admin@exclusive.test',
    password: 'Admin123!',
    role: 'admin',
    isEmailVerified: true,
  },
  {
    name: 'Jane Customer',
    email: 'customer@exclusive.test',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+1 415 555 0123',
  },
  {
    name: 'Adeel Khan',
    email: 'adeel.khan@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+92 300 1234567',
  },
  {
    name: 'Sara Ahmed',
    email: 'sara.ahmed@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+92 321 7654321',
  },
  {
    name: 'Michael Chen',
    email: 'michael.chen@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+1 206 555 0199',
  },
  {
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+91 98765 43210',
  },
  {
    name: 'Omar Farooq',
    email: 'omar.farooq@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+971 50 123 4567',
  },
  {
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+44 7700 900123',
  },
  {
    name: 'Bilal Raza',
    email: 'bilal.raza@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+92 333 1112233',
  },
  {
    name: 'Hannah Müller',
    email: 'hannah.muller@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+49 151 23456789',
  },
  {
    name: 'Daniel Lee',
    email: 'daniel.lee@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+82 10 1234 5678',
  },
  {
    name: 'Fatima Zahra',
    email: 'fatima.zahra@example.com',
    password: 'Customer123!',
    role: 'customer',
    isEmailVerified: true,
    phone: '+212 6 12 34 56 78',
  },
]

/** Reusable sample shipping addresses — the order seed picks from these. */
export const sampleAddresses = [
  { street: '12 Garden Town', city: 'Lahore', state: 'Punjab', zip: '54000', country: 'Pakistan' },
  { street: '45 Clifton Block 5', city: 'Karachi', state: 'Sindh', zip: '75600', country: 'Pakistan' },
  { street: '789 Market Street, Apt 4B', city: 'San Francisco', state: 'CA', zip: '94103', country: 'USA' },
  { street: '23 Brigade Road', city: 'Bengaluru', state: 'Karnataka', zip: '560001', country: 'India' },
  { street: '5 Sheikh Zayed Road', city: 'Dubai', state: 'Dubai', zip: '00000', country: 'UAE' },
  { street: '10 Downing Court', city: 'London', state: 'England', zip: 'SW1A 2AA', country: 'UK' },
  { street: '17 Friedrichstraße', city: 'Berlin', state: 'BE', zip: '10117', country: 'Germany' },
  { street: '88 Gangnam-gu', city: 'Seoul', state: 'Seoul', zip: '06236', country: 'South Korea' },
]
